# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll"
gem "bundler"
gem "github-pages"
gem "webrick", "~> 1.7"
gem "nokogiri", "~> 1.16.0"