name: CI for Jekyll Coding Blog

on:
  push:
    branches: [ master ]
    paths:
      - 'blog/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Ruby and Dependencies
      - name: Install Ruby and Jekyll
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          echo 'export GEM_HOME="$HOME/.gem"' >> $GITHUB_ENV
          echo 'export GEM_PATH="$HOME/.gem"' >> $GITHUB_ENV
          echo 'export PATH="$HOME/.gem/bin:$PATH"' >> $GITHUB_ENV
          source $GITHUB_ENV
          # Force installation of gems to the user directory
          gem install --user-install jekyll bundler

      # Build the Jekyll site
      - name: Build Jekyll site
        run: |
          source $GITHUB_ENV
          cd blog
          jekyll build

      - name: Copy files to web server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: 22
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./blog/_site/*"
          target: "/usr/share/nginx/html/blog/"
          overwrite: true
          strip_components: 2