name: CI for Jekyll Coding Blog

on:
  push:
    branches: [ master ]
    paths:
      - 'blog/**'
      - '.github/workflows/build-jekyll-blog.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build Jekyll site
        working-directory: ./blog
        run: |
          bundle install
          jekyll build

      - name: Copy files to web server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: 22
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./blog/_site/*"
          target: "/usr/share/nginx/html/blog/"
          overwrite: true
          strip_components: 2